version: '3.6'

services:
  web:
    container_name: evekb-web
    build:
      context: .
      dockerfile: ./config/Dockerfile
    networks:
      - evekb
    ports:
      - 3000:3000

networks:
  evekb:
    name: evekb-network
