version: '3.6'

name: evekb

services:
  kb2:
    container_name: evekb-kb2
    build:
      context: .
      dockerfile: ./config/Dockerfile
    networks:
      - evekb
    ports:
      - 4100

networks:
  evekb:
    name: evekb-network
    external: true
