FROM nginx:alpine

COPY ["config/nginx.conf", "/etc/nginx/nginx.conf"]
COPY ["config/nginx.local.conf", "/etc/nginx/conf.d/kb2.conf"]
WORKDIR /app
COPY ./dist /app/dist
EXPOSE 4100

CMD ["nginx", "-g", "daemon off;"]
